server:
  port: 8087

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: madwey.service@gmail.com
    password: vjta fpby tpvu vobf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    queues:
      registration-mail: registration_mail

service:
  activation:
    uri: http://127.0.0.1:8086/user/activation?id={id}

